# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          //registry.npmjs.org/:_authToken: ${{secrets.NPM_TOKEN}}
      - run: npm i -g pnpm
      - run: pnpm install
      - run: npm i -g conventional-changelog-cli
      - run: git config --global user.name "maomiao"
      - run: git config --global user.email "maomiao@mrray.cn"
      - run: lerna version --conventional-commits --preid beta --yes
      - run: lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.PUSH_ACCESS_TOKEN}}
