name: Release Monorepo Package

on:
  # explain what kind of action will trigger the workflow
  push:
    branches:
      - main
    paths:
      - "packages/**.js"

  # manually trigger the workflow
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Global Install pnpm
        run: npm i -g pnpm

      - name: Install Related Package
        run: pnpm install

      - name: Conventional Changelog Install
        run: npm i -g conventional-changelog-cli

      - name: GitHub Authorization
        run: |
          git config --global user.name "maomiao"
          git config --global user.email "maomiao@mrray.cn"

      - name: Release And Tagged Version
        run: lerna version --conventional-commits --yes

      - name: Publish Packages
        run: lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.PUSH_ACCESS_TOKEN}}
